//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareStore.hr {
    
    
    public partial class HRStatistic {
        
        /// <summary>
        /// ctStatisticSTCLevel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftwareStore.hr.Controls.ctStatisticSTCLevel ctStatisticSTCLevel;
        
        /// <summary>
        /// ctStatisticEducation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftwareStore.hr.Controls.ctStatisticEducation ctStatisticEducation;
        
        /// <summary>
        /// ctStatisticMemberAge control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftwareStore.hr.Controls.ctStatisticMemberAge ctStatisticMemberAge;
    }
}
