//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareStore.hr {
    
    
    public partial class UserProfile {
        
        /// <summary>
        /// ctPersonalInformation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftwareStore.hr.Controls.ctPersonalInformation ctPersonalInformation;
        
        /// <summary>
        /// ctEducation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftwareStore.hr.Controls.ctEducation ctEducation;
        
        /// <summary>
        /// ctLanguageAbility control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftwareStore.hr.Controls.ctLanguageAbility ctLanguageAbility;
        
        /// <summary>
        /// ctCertification control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftwareStore.hr.Controls.ctCertification ctCertification;
        
        /// <summary>
        /// ctAward control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftwareStore.hr.Controls.ctAward ctAward;
        
        /// <summary>
        /// ctReward control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftwareStore.hr.Controls.ctReward ctReward;
    }
}
