//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareStore.device {
    
    
    public partial class ConfirmDevice {
        
        /// <summary>
        /// ctTeamConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftwareStore.device.Controls.ctTeamConfirm ctTeamConfirm;
        
        /// <summary>
        /// ctMyConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftwareStore.device.Controls.ctMyConfirm ctMyConfirm;
    }
}
