//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareStore.device.Confirmation {
    
    
    public partial class LeaderInventoryPage {
        
        /// <summary>
        /// ctLeaderNeedAccept control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftwareStore.device.Controls.ctLeaderNeedAccept ctLeaderNeedAccept;
        
        /// <summary>
        /// ctLeaderHasAccepted control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftwareStore.device.Controls.ctLeaderHasAccepted ctLeaderHasAccepted;
        
        /// <summary>
        /// ctLeaderHasRejected control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftwareStore.device.Controls.ctLeaderHasRejected ctLeaderHasRejected;
        
        /// <summary>
        /// ctLeaderUserNotConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftwareStore.device.Controls.ctLeaderUserNotConfirm ctLeaderUserNotConfirm;
    }
}
