<?xml version="1.0" encoding="utf-8"?><Database Name="MNSHOP" Class="CategoryDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=MNSHOP;Integrated Security=True;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="DataAccess.Properties.Settings" SettingsPropertyName="MNSHOPConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbCategory" Member="tbCategories">
    <Type Name="tbCategory">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tbCategory_tbCategory" Member="tbCategories" ThisKey="Id" OtherKey="ParentId" Type="tbCategory" />
      <Association Name="tbCategory_tbCategory" Member="tbCategory1" ThisKey="ParentId" OtherKey="Id" Type="tbCategory" IsForeignKey="true" />
    </Type>
  </Table>
</Database>