//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareStore.device.Confirmation {
    
    
    public partial class UserInventoryPage {
        
        /// <summary>
        /// ctUserNeedConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftwareStore.device.Controls.ctUserNeedConfirm ctUserNeedConfirm;
        
        /// <summary>
        /// ctUserHasConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftwareStore.device.Controls.ctUserHasConfirm ctUserHasConfirm;
        
        /// <summary>
        /// ctUserLeaderAccept control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftwareStore.device.Controls.ctUserLeaderAccept ctUserLeaderAccept;
        
        /// <summary>
        /// ctUserLeaderReject control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SoftwareStore.device.Controls.ctUserLeaderReject ctUserLeaderReject;
    }
}
